version: "3"
services:
  fairy-chess-app:
    image: ratopythonista/fairy_chess:latest
    build: ./
    container_name: fairy-chess-app
    command: bash -c "python fairy_chess"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/fairy_chess
    networks:
      - fairy-chess-network

  fairy-chess-postgres:
    image: postgres:14
    container_name: fairy-chess-postgres
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: fairyc
      POSTGRES_PASSWORD: fc123
    volumes:
     - /var/data/pgsql:/var/data/pgsql/data
    ports:
      - "5432:5432"
    networks:
      - fairy-chess-network


  fairy-chess-minio:
    image: minio/minio
    container_name: fairy-chess-minio
    environment:
      MINIO_ROOT_USER: fairyc
      MINIO_ROOT_PASSWORD: fairychess123
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server --console-address ":9090" /data 
    volumes:
     - /var/data/minio:/data
    networks:
      - fairy-chess-network

  fairy-chess-cache:
    image: redis:6.2-alpine
    container_name: fairy-chess-cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - /var/data/redis:/data
    networks:
      - fairy-chess-network
networks:
  fairy-chess-network:
    driver: bridge
