version: "3"
services:
  fairy_chess:
    image: ratopythonista/fairy_chess:latest
    build: ./
    container_name: fairy_chess
    command: bash -c "python fairy_chess"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/fairy_chess
    networks:
      - fairy-chess-network

networks:
  fairy-chess-network:
    driver: bridge
